Dodano encje rentalItem
xEdziu/Klama pull request #5
Opened 2024-10-21 21:30 UTC by ZuberRS03

Zgadnie z poradnikiem dodałem encje rentalItem.  
Encja zawiera kolumny: id(Long), name(String), description(String), prise(Float), quantity(int).

Do wytestowania:
`POST` z parametrem `Body` jako JSON (http://localhost:8080/api/v1/rentalItem) 
Dodaje przedmiot o podanych parametrach.
przykładowa zawartość w JSON: 
```json
{
  "name": "czekan",
  "description": "jakiś piękny opis",
  "price": 36.7,
  "quantity": 4
}
```

`GET `
http://localhost:8080/api/v1/rentalItem - daje wszystkie przedmioty
http://localhost:8080/api/v1/rentalItem/* - daje przedmiot o konkretnym `ID`

`PUT` z parametrami w linku
Zmieniana jest dowolna ilość parametrów w przedmiocie o podanym `ID`
http://localhost:8080/api/v1/rentalItem/1?name=nowyCzekan&description=jeszcze ładniejszy opis

`DELETE` z parametrem w linku
usuwa przedmiot o podanym `ID`
http://localhost:8080/api/v1/rentalItem/*

2024-10-22 00:02 UTC, xEdziu commented on src/main/java/pwr/isa/klama/rentalItem/RentalItemController.java
> +    @PostMapping
Dodałbym tutaj specyficzną ścieżkę dodawania - np. '/add` - żeby to było jakkolwiek oddzielone :)

2024-10-22 00:04 UTC, xEdziu commented on src/main/java/pwr/isa/klama/rentalItem/RentalItemController.java
> +        rentalItemService.addNewRentalItem(rentalItem);
tutaj też zastanowiłbym się nad jakąkolwiek zwrotką do użytkownika - natomiast to powiem co i jak po moim pull request, gdzie pokaże wam jak takie zwrotki dawać

2024-10-22 00:14 UTC, xEdziu requested changes
Działać działa - to najważniejsze, zmiany raczej kosmetyczne i jedna użytkowa, mało do poprawy, powinno zająć niecałą chwilę :)

overall, bardzo dobra robota

2024-10-22 00:14 UTC, xEdziu commented on src/main/java/pwr/isa/klama/rentalItem/RentalItemController.java
> +            @PathVariable("rentalItemId") Long rentalItemId,
No tutaj zdecydowanie zastanowiłbym się nad `@RequestBody` niż nad `@RequestParam`

2024-10-22 00:14 UTC, xEdziu commented on src/main/java/pwr/isa/klama/rentalItem/RentalItemController.java
> +    @DeleteMapping(path = "{rentalItemId}")
Tutaj dodałbym ścieżkę `/delete/{rentalItemId}`

2024-10-22 00:14 UTC, xEdziu commented on src/main/java/pwr/isa/klama/rentalItem/RentalItemService.java
Jako, że to aplikacja na projekt na uczelnię, dodawajmy od razu wszystkie zwrotki do użytkownika (przynamniej informacje co się dzieje, już te HttpResponse mogą być po angielsku) w języku polskim

2024-11-06 13:52 UTC, ZuberRS03 commented
Jak coś to w pierwszym komentarzu edytowałem tak żeby linki i treść była aktualna

2024-11-06 20:07 UTC, xEdziu commented
![image](https://github.com/user-attachments/assets/9c659f08-0b6f-47de-9e5b-a747f199891d)

Mogę dodać kilkukrotnie ten sam item - czy jest to zamierzone? XD może jakieś sprawdzenie czy np. dany tytuł istnieje czy np. badziej zwiększenie quantity już istniejącego rekordu

2024-11-06 20:14 UTC, xEdziu commented
Plus pytanie - czy chcemy zrobić rozdzielenie na akcje typu użytkownik, admin, ogolnodostępne? 
Przydało by się to @ZuberRS03

2024-11-06 20:14 UTC, xEdziu requested changes
Tutaj pom.xml zmieniłem, żeby już było tak jak jest w moim

2024-11-13 22:33 UTC, ZuberRS03 commented
Dobra prawdopodobnie skończyłem z tę encją, potestuj i w razie co będę łatał. Przesyłam Ci wszystkie moje zapytania.
```xml
<folderState>
                <option name="id" value="21412d3e-c668-451f-adaa-c6d4973da586" />
                <option name="name" value="Rental Items" />
                <option name="requests">
                  <list>
                    <requestState>
                      <option name="description" value="Pobierz wszystkie itemy z wypożyczalni" />
                      <option name="id" value="26d233b6-ca7b-4a21-9b8e-8ef14d95bcb2" />
                      <option name="method" value="GET" />
                      <option name="name" value="All item for Admin" />
                      <option name="sortWeight" value="500000" />
                      <option name="url" value="http://localhost:8080/api/v1/authorized/admin/rentalItem/all" />
                    </requestState>
                    <requestState>
                      <option name="description" value="Pobierz wszyskie aktywne itemy z wypożyczlni" />
                      <option name="id" value="03b92bb6-8168-4dac-8234-c024cd0457ce" />
                      <option name="method" value="GET" />
                      <option name="name" value="All active Items" />
                      <option name="sortWeight" value="1000000" />
                      <option name="url" value="http://localhost:8080/api/v1/rentalItem/all" />
                    </requestState>
                    <requestState>
                      <option name="description" value="Pobierz konkretny item z wypożyczlni" />
                      <option name="id" value="a745e927-a068-4074-8a01-fb5b53124d11" />
                      <option name="method" value="GET" />
                      <option name="name" value="One Item" />
                      <option name="sortWeight" value="2000000" />
                      <option name="url" value="http://localhost:8080/api/v1/rentalItem/1" />
                    </requestState>
                    <requestState>
                      <option name="body">
                        <bodyState>
                          <option name="raw" value="{&#10;  &quot;name&quot;: &quot;zmieniona magnezja&quot;,&#10;  &quot;description&quot;: &quot;opis jakis tam poprawiony&quot;,&#10;  &quot;price&quot;: 16.5,&#10;  &quot;quantity&quot;: 29,&#10;  &quot;status&quot;: &quot;INACTIVE&quot;&#10;}" />
                          <option name="type" value="JSON" />
                        </bodyState>
                      </option>
                      <option name="description" value="Zaaktualizuj item o danym id" />
                      <option name="id" value="fcd2602b-17d5-4bc0-8060-0ea18c23b998" />
                      <option name="method" value="PUT" />
                      <option name="name" value="Update item" />
                      <option name="queryParams">
                        <list>
                          <queryParamState>
                            <option name="disabled" value="true" />
                            <option name="key" value="name" />
                            <option name="value" value="nowyCzekan" />
                          </queryParamState>
                          <queryParamState>
                            <option name="disabled" value="true" />
                            <option name="key" value="description" />
                            <option name="value" value="jeszcze ładniejszy opis" />
                          </queryParamState>
                        </list>
                      </option>
                      <option name="sortWeight" value="3000000" />
                      <option name="url" value="PUT http://localhost:8080/api/v1/authorized/admin/rentalItem/update/1" />
                    </requestState>
                    <requestState>
                      <option name="description" value="Usuń item o danym id" />
                      <option name="id" value="e9cbe742-621f-4ae5-882e-3bf1b82a42eb" />
                      <option name="method" value="DELETE" />
                      <option name="name" value="Deleate item by id" />
                      <option name="sortWeight" value="4000000" />
                      <option name="url" value="http://localhost:8080/api/v1/authorized/admin/rentalItem/delete/1" />
                    </requestState>
                    <requestState>
                      <option name="body">
                        <bodyState>
                          <option name="raw" value="{&#10;  &quot;name&quot;: &quot;worek&quot;,&#10;  &quot;description&quot;: &quot;jakiś piękny opis worka&quot;,&#10;  &quot;price&quot;: 12.3,&#10;  &quot;quantity&quot;: 5,&#10;  &quot;status&quot;: &quot;ACTIVE&quot;,&#10;}" />
                          <option name="type" value="JSON" />
                        </bodyState>
                      </option>
                      <option name="description" value="Dodaj przedmiot do wypożyczlni" />
                      <option name="id" value="e9077354-50d9-46c6-a259-7e28ad9dbb24" />
                      <option name="method" value="POST" />
                      <option name="name" value="Add new item" />
                      <option name="sortWeight" value="5000000" />
                      <option name="url" value="http://localhost:8080/api/v1/authorized/admin/rentalItem/add" />
                    </requestState>
                    <requestState>
                      <option name="body">
                        <bodyState>
                          <option name="raw" value="{&#10;  &quot;rentRequests&quot;: [&#10;    {&#10;      &quot;itemId&quot;: 1,&#10;      &quot;quantity&quot;: 2&#10;    },&#10;    {&#10;      &quot;itemId&quot;: 2,&#10;      &quot;quantity&quot;: 1&#10;    }&#10;  ],&#10;  &quot;rentDate&quot;: &quot;2024-12-01T10:00:00.000Z&quot;,&#10;  &quot;returnDate&quot;: &quot;2025-01-05T10:00:00.000Z&quot;&#10;}" />
                          <option name="type" value="JSON" />
                        </bodyState>
                      </option>
                      <option name="description" value="Wypożycz kilka itemów w kilku sztukach" />
                      <option name="id" value="0ebdd99f-e704-4b7a-8b01-5450f4a2ec59" />
                      <option name="method" value="POST" />
                      <option name="name" value="Rent Many-Many" />
                      <option name="sortWeight" value="6000000" />
                      <option name="url" value="http://localhost:8080/api/v1/authorized/rentalItem/rent" />
                    </requestState>
                    <requestState>
                      <option name="body">
                        <bodyState>
                          <option name="raw" value="{&#10;  &quot;rentRequests&quot;: [&#10;    {&#10;      &quot;itemId&quot;: 1,&#10;      &quot;quantity&quot;: 1&#10;    }&#10;  ],&#10;  &quot;rentDate&quot;: &quot;2024-12-01T10:00:00.000Z&quot;,&#10;  &quot;returnDate&quot;: &quot;2025-01-05T10:00:00.000Z&quot;&#10;}" />
                          <option name="type" value="JSON" />
                        </bodyState>
                      </option>
                      <option name="description" value="Wypożycz jeden item w jednej sztuce" />
                      <option name="id" value="0ceef2df-332e-4f0d-ad55-34702745d86a" />
                      <option name="method" value="POST" />
                      <option name="name" value="Rent 1-1" />
                      <option name="sortWeight" value="7000000" />
                      <option name="url" value="http://localhost:8080/api/v1/authorized/rentalItem/rent" />
                    </requestState>
                    <requestState>
                      <option name="body">
                        <bodyState>
                          <option name="raw" value="{&#10;  &quot;rentRequests&quot;: [&#10;    {&#10;      &quot;itemId&quot;: 1,&#10;      &quot;quantity&quot;: 3&#10;    }&#1 [...]

2024-11-14 03:34 UTC, xEdziu requested changes
Pewnie masz mnie już dość, ale to tylko drobne błędy/literówki. Tylko jedna rzecz wymaga większej uwagi - API potestowałem tyle ile dałem radę, nie znalazłem czegoś więcej do czego mógłbym się przyczepić :))

2024-11-14 03:34 UTC, xEdziu commented on src/main/java/pwr/isa/klama/rentalItem/RentalItemService.java
> +            throw new IllegalArgumentException("Przedmiot o id " + rentalItemId + " nie istnieje");
![image](https://github.com/user-attachments/assets/7fdc93ae-908a-41b3-9a5b-37e5acf48eb0)


1. Nie `IlleagalArgument` tylko, `IllegalState` - obsługujemy drugi błąd, który zwraca `401`, a nie `500`
2. To chyba podlega pod `ResourceNotFoundException` :D

2024-11-14 03:34 UTC, xEdziu commented on src/main/java/pwr/isa/klama/rentalItem/RentalItemService.java
> +            throw new IllegalStateException("Przedmiot o id " + rentalItemId + " jest/był wypożyczony i nie może zostać usunięty");
![image](https://github.com/user-attachments/assets/cc6ede5a-789f-46ab-9b34-c6abb16a01bf)

Nie robiłbym tego w ten sposób - może po prostu zdeaktywować ten element? żeby tak czy siak był w historii wypożyczeń, ale nie możliwy do dalszego wypożyczenia?

2024-11-14 03:34 UTC, xEdziu commented on src/main/java/pwr/isa/klama/rentalItem/RentalItemService.java
> +            throw new IllegalArgumentException("Przedmiot o nazwie: " + rentalItem.getName() + " już istnieje");
![image](https://github.com/user-attachments/assets/d4f769da-9dc2-40d1-944c-25b1011f3f0a)

Znów `IllegalState` powinien być zamiast `IllegalArgument`

2024-11-14 03:34 UTC, xEdziu commented on src/main/java/pwr/isa/klama/rentalItem/RentalItemService.java
> +            throw new IllegalStateException("Przedmiot o id " + rentalItemId + " nie istnieje");
![image](https://github.com/user-attachments/assets/9d1d63b4-0266-4d3e-a1de-4688b8ee5057)

a tutaj `ResourceNotFoundException`

2024-11-14 03:34 UTC, xEdziu commented on src/main/java/pwr/isa/klama/rentalItem/RentalItemService.java
> +            throw new IllegalArgumentException("Przedmiot o id " + rentalItemId + " nie istnieje");
`ResourceNotFoundException` :D

2024-11-14 03:34 UTC, xEdziu commented on src/main/java/pwr/isa/klama/rentalItem/RentalItemService.java
> +                throw new IllegalStateException("Cena nie możę być pusta");
literówka

2024-11-14 03:34 UTC, xEdziu commented on src/main/java/pwr/isa/klama/rentalItem/RentalItemService.java
> +            throw new IllegalArgumentException("Należy podać jeden z parametrów");
`IllegalState`

2024-11-14 03:34 UTC, xEdziu commented on src/main/java/pwr/isa/klama/rentalItem/RentalItemService.java
> +                .orElseThrow(() -> new IllegalStateException("Przedmiot o id " + rentalItemId + " nie istnieje"));
`ResourceNotFound`

2024-11-14 08:50 UTC, xEdziu approved these changes

2024-11-14 08:50 UTC, merged