Rejestracja i Posty
xEdziu/Klama pull request #8
Opened 2024-10-22 04:38 UTC by xEdziu

#  Zmiany

- przede wszystkim, dodałem system rejestracji użytkowników.

    W skład tego wchodzi również system aktywacji konta
 oraz system wysyłania maili do użytkowników.
- została dodana klasa konfiguracyjna, która na starcie aplikacji dodaje do bazy danych
jednego użytkownika - administratora.
- rozdzieliłem API na 3 poziomy dostępu:
1.  Ogólnodostępne
2. Tylko dla zalogowanych użytkowników
3. Tylko dla Administratorów
- dodałem customową obsługę błędów w pliku `CustomExceptionHandler`
oraz dodałem konfigurator bezpieczństwa aplikacji: `WebSecurityConfig`
- każdy z endpointów API zwraca teraz ładnego JSON-a w formacie:
```json
{
  "message": "Wiadomość",
  "timestamp": "Data i godzina",
  "status": 200
  "error": "Nazwa błędu",
  "path": "Ścieżka z której został wywołany endpoint w przypadku błędu"
}
```
> Kod statusu zwraca jako kod HTTP

chyba, że zwraca jakieś dane - wtedy zwraca JSON-a z danymi.

- utworzyłem dwie klasy typu DTO: `UserDTO` oraz `PostDTO` do obsługi
wyświetlania danych użytkowników oraz postów, bez wyświetlania danych niepotrzebnych
dla użytkownika.

- dodałem dwa nowe customowe wyjątki: `AccountNotActivatedException` oraz `ResourceNotFoundException`
zwracające odpowiednio statusy HTTP 403 oraz 404.

# Testowanie nowych funkcji

## Posty
### Metoda GET
#### Pobranie wszystkich postów
- ogólnodostępne
- zwraca listę wszystkich postów
- odwołanie do endpointu: `GET http://localhost:8080/api/v1/posts`
- brak dodatkowych parametrów ani Body

#### Pobranie postu po ID
- ogólnodostępne
- zwraca post o podanym ID
- odwołanie do endpointu: `GET http://localhost:8080/api/v1/posts/{id}`
- brak dodatkowych parametrów ani Body

### Metoda POST
#### Dodanie nowego postu
- tylko dla administratorów
- dodaje nowy post, zwraca status operacji
- odwołanie do endpointu: `POST http://localhost:8080/api/v1/authorized/admin/posts/add`
- Body:
```json
{
  "title": "Tytuł posta",
  "content": "Treść posta",
  "authorId": 1
}
```
> `authorId` - ID autora posta, tutaj jest dodane stałe ID, ale w przyszłości
> zostanie zastąpione przez ID zalogowanego użytkownika (administratora)

### Metoda PUT
#### Edycja postu
- tylko dla administratorów
- edytuje post o podanym ID, zwraca status operacji
- odwołanie do endpointu: `PUT http://localhost:8080/api/v1/authorized/admin/posts/update/{postId}`
-  Body:
```json
{
  "content": "This is a put request to update the post"
}
```
lub
```json
{
  "title": "This is a put request to update the post"
}
```
lub oba:
```json
{
  "title": "This is a put request to update the post",
  "content": "This is a put request to update the post"
}
```

### Metoda DELETE
#### Usunięcie postu
- tylko dla administratorów
- usuwa post o podanym ID, zwraca status operacji
- odwołanie do endpointu: `DELETE http://localhost:8080/api/v1/authorized/admin/posts/delete/{postId}`
- brak dodatkowych parametrów ani Body

## Użytkownicy
### Metoda GET
#### Potwierdzenie emaila użytkownika
- ogólnodostępne
- potwierdza email użytkownika, zwraca status operacji
- odwołanie do endpointu: `GET http://localhost:8080/api/v1/register/confirm?token={token}`
- parametry URL:
    - `token` - token aktywacyjny wysłany na email użytkownika

#### Pobranie jednego użytkownika po ID
- tylko dla zalogowanych użytkowników
- zwraca dane jednego użytkownika
- odwołanie do endpointu: `GET http://localhost:8080/api/v1/authorized/user/{id}`
- brak dodatkowych parametrów ani Body
> W przypadku próby pobrania danych administratora, zwróci błąd `400`

#### Pobranie wszystkich użytkowników
- tylko dla administratorów
- zwraca listę wszystkich użytkowników
- odwołanie do endpointu: `GET http://localhost:8080/api/v1/authorized/admin/user/all`
- brak dodatkowych parametrów ani Body

#### Pobranie użytkownika po Id - dla administratora
- tylko dla administratorów
- zwraca dane jednego użytkownika
- odwołanie do endpointu: `GET http://localhost:8080/api/v1/authorized/admin/user/{id}`
- brak dodatkowych parametrów ani Body

### Metoda POST
#### Rejestracja nowego użytkownika
- ogólnodostępne
- dodaje nowego użytkownika, zwraca status operacji
- odwołanie do endpointu: `POST http://localhost:8080/api/v1/register/signup`
- Body:
```json
{
  "username": "nick",
  "firstName": "imię",
  "surname": "nazwisko",
  "email": "mail@mail.com",
  "password": "hasło"
}
```
> Dodatkowo zaimplementowana jest walidacja adresu email
> 
> Hasło planuję sprawdzać na poziomie frontendu, więc nie ma walidacji długości hasła itp.

### Metoda PUT
#### Edycja danych użytkownika
- tylko dla zalogowanych użytkowników
- edytuje dane użytkownika, zwraca status operacji
- odwołanie do endpointu: `PUT http://localhost:8080/api/v1/authorized/user/update/{userId}`
- Body:
```json
{
  "username": "nick",
  "firstName": "imię",
  "surname": "nazwisko",
  "email": "mail@mail.com",
  "password": "hasło"
}
```
> Body jest identyczne jak przy dodawaniu nowego użytkownika
>
> W przypadku próby modyfikowania danych administratora zwróci błąd `400`

#### Edycja danych użytkownika - dla administratora

- tylko dla administratora
- edytuje dane użytkownika, zwraca status operacji
- odwłoanie do endpointu: `PUT http://localhost:8080/api/v1/authorized/admin/user/update/{userId}`
- Body identyczne jak wyżej

### Metoda DELETE
#### Usuwanie użytkownika

- tylko dla zalogowanych użytkowników
- usuwa dane użytkownika, zwraca status operacji
- odwłoanie do endpointu: `DELETE http://localhost:8080/api/v1/authorized/user/delete/{userId}`
- brak dodatkowych parametrów lub Body
>W przypadku próby usunięcia administratora wyrzuci błąd `400`

#### Usuwanie użytkownika - dla administratora
- tylko dla administratora
- usuwa dane użytkownika, zwraca status operacji
- odwołanie do endpointu `DELETE http://localhost:8080/api/v1/authorized/admin/user/delete/{userId}`
- brak dodatkowych parametrów lub Body

> Mogą być błędy w odwołaniach tutaj, ale je w razie czego wiesz jak sprawdzić - robię to po całej nocce, więc musisz mi wybaczyć ewentualne niedoskonałości xD

2024-10-26 19:00 UTC, ZuberRS03 commented
Nie działa mi poprawnie pobranie użytkownika po ID dla admina, zwrokta jest taka mimo że użytkownik o takim ID jest w bazie:
```josn
{
  "timestamp": "2024-10-26T18:58:55.508+00:00",
  "status": 404,
  "error": "Not Found",
  "message": "No static resource api/v1/authorized/admin/user/3.",
  "path": "/api/v1/authorized/admin/user/3"
}
```

2024-10-26 19:03 UTC, ZuberRS03 commented
Nie działa mi również usuwanie admina, taką zwrotkę dostaję:
```josn
{
  "timestamp": "2024-10-26T19:01:27.831+00:00",
  "status": 500,
  "error": "Internal Server Error",
  "message": "could not execute statement [Cannot delete or update a parent row: a foreign key constraint fails (`klama`.`post`, CONSTRAINT `FK12njtf8e0jmyb45lqfpt6ad89` FOREIGN KEY (`author_id`) REFERENCES `user` (`id`))] [delete from user where id=?]; SQL [delete from user where id=?]; constraint [null]",
  "path": "/api/v1/authorized/admin/user/delete/1"
}
```

2024-10-26 19:04 UTC, xEdziu commented
> Nie działa mi poprawnie pobranie użytkownika po ID dla admina, zwrokta jest taka mimo że użytkownik o takim ID jest w bazie:
> 
> ```
> {
>   "timestamp": "2024-10-26T18:58:55.508+00:00",
>   "status": 404,
>   "error": "Not Found",
>   "message": "No static resource api/v1/authorized/admin/user/3.",
>   "path": "/api/v1/authorized/admin/user/3"
> }
> ```

sprawdź proszę teraz czy zadziała

2024-10-26 19:17 UTC, xEdziu commented
> Nie działa mi również usuwanie admina, taką zwrotkę dostaję:
> 
> ```
> {
>   "timestamp": "2024-10-26T19:01:27.831+00:00",
>   "status": 500,
>   "error": "Internal Server Error",
>   "message": "could not execute statement [Cannot delete or update a parent row: a foreign key constraint fails (`klama`.`post`, CONSTRAINT `FK12njtf8e0jmyb45lqfpt6ad89` FOREIGN KEY (`author_id`) REFERENCES `user` (`id`))] [delete from user where id=?]; SQL [delete from user where id=?]; constraint [null]",
>   "path": "/api/v1/authorized/admin/user/delete/1"
> }
> ```

Co prawda nie planowałem usuwania admina, ale to dobra rzecz. Wymyślę coś żeby to naprawić, ale jak już to jutro :)

2024-10-26 19:18 UTC, ZuberRS03 commented
> > Nie działa mi poprawnie pobranie użytkownika po ID dla admina, zwrokta jest taka mimo że użytkownik o takim ID jest w bazie:
> > ```
> > {
> >   "timestamp": "2024-10-26T18:58:55.508+00:00",
> >   "status": 404,
> >   "error": "Not Found",
> >   "message": "No static resource api/v1/authorized/admin/user/3.",
> >   "path": "/api/v1/authorized/admin/user/3"
> > }
> > ```
> 
> sprawdź proszę teraz czy zadziała

Faktycznie już śmiga

2024-10-26 19:19 UTC, ZuberRS03 commented
Poza tym jak jest usuwanie admina to nie przydało by się jakieś zabezpieczenie np że nie może być mniej niż jeden admin i opcja dodawania adminów?

2024-10-26 19:22 UTC, xEdziu commented
No właśnie mamy trzy opcje:
1. Przypisanie postów innej domyślnej postaci lub administratorowi
2. Usunięcie wszystkich powiązanych rekordów
> Ta opcja powoduje utratę danych, więc warto ją rozważyć tylko wtedy, gdy nie jest istotne, aby posty istniały po usunięciu ich autora
3. Uniemożliwienie usunięcia ostatniego administratora

którą opcję chcemy rozważyć?

2024-10-26 19:24 UTC, ZuberRS03 commented
> No właśnie mamy trzy opcje:
> 
> 1. Przypisanie postów innej domyślnej postaci lub administratorowi
> 2. Usunięcie wszystkich powiązanych rekordów
> 
> > Ta opcja powoduje utratę danych, więc warto ją rozważyć tylko wtedy, gdy nie jest istotne, aby posty istniały po usunięciu ich autora
> 
> 3. Uniemożliwienie usunięcia ostatniego administratora
> 
> którą opcję chcemy rozważyć?

Albo stokowo w konfigu dodanie jednego admina( takiego roota) byłby nieusuwalny i w przypadku usunięcia admina wszystkie posty przechodziły by na niego

2024-10-26 19:25 UTC, xEdziu commented
Czyli opcja 1 powiązana z 3 - jeden admin techniczny, na którego wszystko przechodzi?

2024-10-26 19:26 UTC, ZuberRS03 commented
> Czyli opcja 1 powiązana z 3 - jeden admin techniczny, na którego wszystko przechodzi?

no coś takiego, byłaby opcja stworzenia innego admina ale ten pierwszy byłby taki "zabetonowany"

2024-10-28 13:05 UTC, ZuberRS03 requested changes
To co opisane w komentarzach

2024-11-06 11:33 UTC, ZuberRS03 commented
Nie wiem czy to zamierzone ale nie mogę usunąć konta użytkownika w momencie kiedy są do niego przypisane jakieś posty, ale nie moge tego zrobić tylko usuwaniem z poziomu zwykłego usera, z poziomu admina już działa i jego posty przepisują się na głównego admina. Tak miało być?

2024-11-06 11:36 UTC, xEdziu commented
Nooo użytkowników może usuwać tylko admin i posty powinien moc wstawiać tez tylko admin - póki co to może nie być zabezpieczone, ale można się tym zająć

2024-11-06 11:44 UTC, ZuberRS03 commented
> Nooo użytkowników może usuwać tylko admin i posty powinien moc wstawiać tez tylko admin - póki co to może nie być zabezpieczone, ale można się tym zająć

No dobra, tylko puki użytkownik nie ma postów to można go usunąć z poziomu usera. Ale dobra poza tym jest git czyli mogę chyba Ci puścić tego pulla

2024-11-06 19:50 UTC, xEdziu commented
> > Nooo użytkowników może usuwać tylko admin i posty powinien moc wstawiać tez tylko admin - póki co to może nie być zabezpieczone, ale można się tym zająć
> 
> No dobra, tylko póki użytkownik nie ma postów to można go usunąć z poziomu usera. Ale dobra poza tym jest git czyli mogę chyba Ci puścić tego pulla

Wiesz co, to jest zrobione z jednego powodu - użytkownik musi mieć prawo usunąć swoje konto - jeszcze pomyślimy nad zabezpieczniem tego w jakiś sposób

2024-11-06 20:21 UTC, ZuberRS03 approved these changes

2024-11-06 20:22 UTC, merged